spring:
  application:
    name: brewery-orchestrator-dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/supply_chain_dev
    username: postgres
    password: dev_password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
  
  liquibase:
    enabled: false

logging:
  level:
    root: INFO
    com.homelab.brewery: DEBUG
    org.springframework.web: DEBUG
